name: Release

on:
  push:
    branches:
      - develop

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn

      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Release Tag
        uses: anothrNick/github-tag-action@1.26.0
        if: success()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ env.CHANGESET_RELEASE_VERSION }}
          message: "Version v${{ env.CHANGESET_RELEASE_VERSION }}"
          ref: ${{ github.ref }}
